### ISSUE TITLE
这是带有DEMO的吗？！

### ISSUE THREAD

**Issue by XieLinMofromsomewhere** [bqFirst/OpenPose-2sAGCN#1]
另外问一问有没有权重文件呢，期待能有一个更加详细的README，感谢分享！

**Comment by bqFirst** [comment]
识别效果很差，现在没有继续优化，权重文件指的是？

**Comment by sunfeng90** [comment]
期待更新一下ReadME

**Comment by Gavin666Github** [comment]
> 识别效果很差，现在没有继续优化，权重文件指的是？

可以使用alphapose识别姿态，效果好很多
